name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/coding-standards.yml
      - bin/**
      - composer.*
      - src/**
      - phpcs.xml.dist
      - tests/**
  push:

jobs:
  coding-standards:
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@5.0.1"
